spring:
  application:
    name: multi-schema-unittest-example
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.HSQLDialect
    hibernate:
      ddl-auto: create-drop
  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:mem:data